name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/*  # Include feature branches
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Run tests
        run: go test ./...

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract tag based on branch or tag
        id: extract_tag
        run: |
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            # For tags (e.g., v1.0.2)
            VERSION=${GITHUB_REF#refs/tags/v}
            echo "TAG=${{ secrets.DOCKERHUB_USERNAME }}/kyc-match-api:${VERSION}" >> $GITHUB_ENV
            echo "LATEST_TAG=${{ secrets.DOCKERHUB_USERNAME }}/kyc-match-api:latest" >> $GITHUB_ENV
          else
            # For branches (e.g., feature/readme-and-docs -> feature-readme-and-docs)
            BRANCH=$(echo ${{ github.ref_name }} | sed 's/\//-/g')
            echo "TAG=${{ secrets.DOCKERHUB_USERNAME }}/kyc-match-api:${BRANCH}" >> $GITHUB_ENV
            echo "LATEST_TAG=" >> $GITHUB_ENV  # No latest tag for branches
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.TAG }}
            ${{ env.LATEST_TAG }}
          platforms: linux/amd64,linux/arm64