name: CI/CD Pipeline
on:
  push:
    branches: [ main, 'feature/*' ]  # Include feature branches
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    - name: Test
      run: go test ./...
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker image
      run: |
        if [[ "${{ github.ref }}" =~ ^refs/tags/v ]]; then
          TAG=${{ github.ref_name }}
          docker build -t balu1921/kyc-match-api:${TAG} -t balu1921/kyc-match-api:latest .
          docker push balu1921/kyc-match-api:${TAG}
          docker push balu1921/kyc-match-api:latest
        else
          BRANCH_TAG=$(echo "${{ github.ref_name }}" | tr '/' '-')
          docker build -t balu1921/kyc-match-api:${BRANCH_TAG} .
          docker push balu1921/kyc-match-api:${BRANCH_TAG}
        fi